boxine/bx_django_utils

bx_django_utils/models/manipulate.py
bx_django_utils_tests/tests/test_model_manipulate.py

`create` should crash if the object exists already.

Avoid create() updating objects

---

bx_django_utils/models/color_field.py

This is in preparation for Django 4, where the ugettext variant is being removed (now all strings are unicode in Python).

ugettext -> gettext

---

bx_django_utils_tests/tests/test_json_utils.py

pytest freaks out
```
.:0
:0: PytestCollectionWarning: cannot collect test class 'TestObject' because it has a __init__ constructor (from: bx_django_utils_tests/tests/test_json_utils.py)
-- Docs: https://docs.pytest.org/en/stable/warnings.html
```
There are no tests in this class, mark it as such to get rid of the warning.

Remove pytest warning

---

README.md
bx_django_utils/test_utils/content_types.py
bx_django_utils_tests/tests/test_content_types_utils.py

TestCase mixin to fill the ContentType cache to avoid flaky database queries.
The Problem is, that the ContentTypeManager used a shared cache for lookups.
If your tests checks the made database queries, then you may get different results
depending on how the cache is filled.
With this Mixin the ContentTypeManager cache is always filled and all tests will never
hit the databases...

NEW: ContentTypeCacheFixMixin for TestCases

---

README.md
bx_django_utils/models/queryset_utils.py
bx_django_utils_tests/tests/test_model_queryset_utils.py

Error without this PR, looks like:
```
node = <django.db.models.sql.where.NothingNode object at 0x7fe8ab53b640>
def filter_lookups(node):
if hasattr(node, 'lhs'):
return node.lhs.target != clause.children[0].lhs.target
>       return len(list(filter(filter_lookups, node.children))) == len(node.children)
E       AttributeError: 'NothingNode' object has no attribute 'children'
clause     = <WhereNode: (AND: <django.db.models.lookups.IsNull object at 0x7fe8ab53bd60>)>
filter_lookups = <function remove_filter.<locals>.filter_lookups at 0x7fe8ab539040>
node       = <django.db.models.sql.where.NothingNode object at 0x7fe8ab53b640>
bx_django_utils/models/queryset_utils.py:28: AttributeError
```

Bugfix remove_filter() for empty querysets

---

README.md
bx_django_utils/test_utils/assert_queries.py
bx_django_utils_tests/tests/test_assert_queries.py

This can be used to exclude irrelevant counts, such as permissions, ContentTypes etc. .
Also allow passing in plain dicts instead of Counters.

assert_table_counts: Add an option to exclude tables

---

README.md
bx_django_utils/test_utils/assert_queries.py
bx_django_utils_tests/tests/test_assert_queries.py

old error looks like:
```
table_names = re.findall(r'(FROM|INSERT INTO|UPDATE) \"(.+?)\"', sql)
>           assert len(table_names) == 1, f'Error parsing: {sql!r}'
E           AssertionError: Error parsing: 'SELECT COUNT(*) AS "__count" FROM "auth_group" INNER
JOIN "auth_group_permissions" ON ("auth_group"."id" = "auth_group_permissions"."group_id") WHERE
"auth_group_permissions"."permission_id" IN (SELECT U0."id" FROM "auth_permission" U0 INNER JOIN
"django_content_type" U1 ON (U0."content_type_id" = U1."id") WHERE U1."app_label" =
\'\'\'not-exist\'\'\')'
```

Bugfix AssertQueries() if INNER JOIN with another tables ;)

---

README.md
bx_django_utils/test_utils/html_assertion.py
bx_django_utils_tests/tests/test_html_assertion.py

Add a function to not compare all Django messages statically, but snapshot them.

+ snapshot_messages function

---

README.md
bx_django_utils/models/queryset_utils.py
bx_django_utils_tests/tests/test_model_queryset_utils.py

This method functions similar to `remove_filter`, but also allows deletion of checks on related models.

+ remove_model_filter method

---

README.md
bx_django_utils/test_utils/html_assertion.py
bx_django_utils_tests/tests/test_html_assertion.py

- `assert_html_response_snapshot` will now only snapshot the `#content` container by default (can be overridden by setting the `query_selector=""` argument

ues assert_html_snapshot in assert_html_response_snapshot and default to #content container

---

.github/workflows/pythonapp.yml
Makefile
bx_django_utils_tests/tests/test_html_assertion.py
poetry.lock
pyproject.toml

Run tests against Python 3.8-3.10 and Django 3.2 and 4.0
(But still keep Python 3.7 support, enforce it in the future)
Use darker and pytest-daker.
Remove tox-poetry-installer.

Update CI/test setup

---

bx_django_utils/test_utils/playwright.py

use `AbstractUser` instead of `User` as type annotation for Django users. Users are a swappable model, so users of bx_django_util may pass instances of their own user model!

use `AbstractUser` instead of `User` as type annotation for Django users

---

README.md
bx_django_utils/test_utils/assert_queries.py
bx_django_utils_tests/tests/test_assert_queries.py
bx_django_utils_tests/tests/test_assert_queries_snapshot_table_counts_1.snapshot.json
bx_django_utils_tests/tests/test_assert_queries_snapshot_table_counts_2.snapshot.json

Add a helper function to snapshot the table counts of queries, for when we have a large query table count assertion that often changes, e.g. for importing all languages.

+ snapshot_table_counts

---

bx_django_utils/templatetags/humanize_time.py

Fixes deprecation warning on Django 4.1:
`RemovedInDjango50Warning: The django.utils.timezone.utc alias is deprecated. Please update your code to use datetime.timezone.utc instead.`

use datetime.timezone.utc instead of django util

---

bx_django_utils_tests/test_project/settings.py

Clarify why we set "DJANGO_ALLOW_ASYNC_UNSAFE", see: https://github.com/microsoft/playwright-python/issues/439#issuecomment-763339612

Clarify about "DJANGO_ALLOW_ASYNC_UNSAFE"

---

bx_django_utils_tests/tests/test_readme.py
poetry.lock
pyproject.toml

* Update requirements
* Remove `python = ">=3.7"` for `pdoc` (We didn't support 3.7)
* Bugfix pytest by remove `--import-mode=importlib`
* Preparation: Exclude all `*/migrations/*` files from README

Some small updates

---

README.md
bx_django_utils/test_utils/fixtures.py

When we test something with the fixtures, or don't have the credentials for all fixtures, we only want to update one or two.
Add a filter-argument that matches the filename or classname with a regular expression.

Allow filtering fixtures to update

---

README.md
bx_django_utils/test_utils/fixtures.py
bx_django_utils_tests/test_app/tests/test_fixtures_helper.py
bx_django_utils_tests/test_app/tests/test_fixtures_helper_renew_all_1.snapshot.txt
bx_django_utils_tests/test_app/tests/test_fixtures_helper_renew_all_with_regex_1.snapshot.txt
bx_django_utils_tests/test_app/tests/test_fixtures_helper_renew_command_1.snapshot.txt
bx_django_utils_tests/test_app/tests/test_fixtures_helper_select_fixtures_1.snapshot.txt
bx_django_utils_tests/test_app/tests/test_fixtures_helper_select_fixtures_2.snapshot.txt
pyproject.toml

Calling `./manage.sh renew_fixtures` without `--all` will display a list of all registered fixtures and the user can "select" them by input space seperated list of numbers. Looks like:
```
Found 2 fixtures files.
Please select:
0 - ExampleFixtures1
1 - ExampleFixtures2
(ENTER nothing for renew all fixtures)
Input one or more numbers seperated with spaces:
```
It can be combined with the existing `--filter REGEX` and the "select question" can be skipped by using `--all` argument.

Enhance RenewAllFixturesBaseCommand(): User can select fixtures by input

---

README.md
bx_django_utils/feature_flags/data_classes.py
bx_django_utils/feature_flags/test_utils.py
bx_django_utils/feature_flags/tests/test_feature_flags.py
bx_django_utils/feature_flags/tests/test_test_utils.py
bx_django_utils_tests/tests/test_feature_flag_integration.py

Before this PR the state of a FeatureFlag was only stored into the cache on state change.
The result is, that every `.is_enabled` call will hit the database until the state was change for
the first time.
Change this and store the state to cache + database on first usage.
Also set a per-process and thread-safe cache backend for tests. This is needed if tests runs with
`--parallel` add.
Ass helper `get_feature_flag_cache_info()` and `get_feature_flag_db_info()` Think they are only
needed in own tests, so i didn't add a DocString to hide them from README.

Optimize FeatureFlag caching and bugfix FeatureFlagTestCaseMixin

---

.github/workflows/pythonapp.yml
README.md
bx_django_utils/translation.py
bx_django_utils_tests/tests/__init__.py
bx_django_utils_tests/tests/test_translation.py
pyproject.toml

raise `ValidationError` if unknown translations should be stored. For normal usage this should never
happen, because the user get's a form only with known languages.
Before this PR the `_reduce_to_known_languages()` is a kind of suppressed error: It just removed all
"unknown" lanuages, but totally silent. Because of this, I spent a long time looking for a bug in my
own code. But I had only used an unsupported language in the test.
Bind '<UNTRANSLATED>' string to `FieldTranslation.UNTRANSLATED` so it can be used from external code
to compare.
Add a `FieldTranslation.__repr__` and make it helpful for compare in tests.
Add more tests and set `unittest.util._MAX_LENGTH` for better test output.

Enhance translation helper

---

README.md
bx_django_utils/models/manipulate.py
bx_django_utils/translation.py
bx_django_utils_tests/tests/test_model_manipulate.py
bx_django_utils_tests/tests/test_translation.py
pyproject.toml

Store information about changed field values in `CreateOrUpdateResult.update_info` created by `create_or_update2()`
It's a list of `FieldUpdate` and looks like:
```
self.assertEqual(
result.update_info,
[
FieldUpdate(field_name='field1', old_value='before', new_value='after'),
FieldUpdate(field_name='field2', old_value='old', new_value='new'),
],
)
```
Also expand `create_or_update2()` and accept a optional callback that handle the "set new value" step. Use `update_model_field()` as default, that has the behavior. So this change is full backward compatible.
Add a special `create_or_update2()` callback for our `TranslationField` JSON model field: This will merge the existing translations with the new one. So that no existing translation will be removed!

New: CreateOrUpdateResult.update_info and create_or_update2 callbacks for TranslationField

---

bx_django_utils/translation.py
bx_django_utils_tests/tests/test_translation.py
bx_django_utils_tests/tests/test_translation_language_codes_order_1.snapshot.html
pyproject.toml

It was a bad idea to convert the `language_codes` into a `frozenset` because we lost the origin order.
Add a test that checks the order.

Bugfix TranslationWidget ordering

---

bx_django_utils/translation.py
pyproject.toml

By mistake, we used https://pypi.org/project/python-slugify/ Just switch to Django's `slugify()`

slugify -> django.utils.text.slugify

---

README.md
bx_django_utils/translation.py
bx_django_utils_tests/tests/test_translation.py

`assert slug` raised if the source text for the slug contains only special characters. Expand the assertion error and handle this special case in `slug_generator()`

Bugfix TranslationSlugField and handle if source is empty

---

manage.sh

Running `./manage.sh` without poetry installed outputs
```
./manage.sh run_testserver
+ poetry run python --version
./manage.sh: 5: poetry: not found
+ poetry run django-admin --version
./manage.sh: 6: poetry: not found
./manage.sh: 9: exec: poetry: not found
make: *** [Makefile:78: start-dev-server] Error 127
```
This can't be right, abort if we can't even run python.

Crash if no poetry

---

README.md
bx_django_utils/translation.py
bx_django_utils_tests/tests/test_translation.py

When one specific translation is extracted, don't touch the already-good database value.

Handle key transforms

---

README.md
bx_django_utils/models/queryset_utils.py
bx_django_utils_tests/tests/test_model_queryset_utils.py
pyproject.toml

Previously, there were crashes with
`AttributeError: 'KeyTextTransform' object has no attribute 'target'`

remove_model_filter: Fix KeyTextTransform (TOC-7250)

---

bx_django_utils/test_utils/assert_queries.py
bx_django_utils_tests/tests/test_assert_queries.py
pyproject.toml

a M2M `set()` will result in e.g.: `INSERT OR IGNORE INTO...` and `f'Error parsing: {sql!r}'` will be raised. Add support this, too.

Bugfix AssertQueries.get_table_name() for M2M update query

---

README.md
bx_django_utils/version.py

Nobody ever wants to write "unknown" as a version file – better to not write a version file at all and determine it on runtime.

version command: Imply --raise-error when --write-file is given

---

README.md
bx_django_utils/templatetags/humanize_time.py
bx_django_utils_tests/tests/test_templatetags_humanize_time.py
pyproject.toml

Because `timezone.now()` can be easier mocked ;)
Also support all mixes of `datetime` vs. `date` and timezone aware vs. naive variants. Modernize and expand tests.

Use timezone.now() in human_duration()

---

README.md
bx_django_utils/test_utils/assert_queries.py
bx_django_utils_tests/tests/test_assert_queries.py
pyproject.toml

Add "Got these counts:" section with copy&paste friendly text. Looks like:
```
Table count error:
--- expected table counts
+++ current table counts
@@ -1,2 +1,3 @@
-auth_permission: 3
-foo: 1
+auth_group: 1
+auth_permission: 2
+django_admin_log: 1
Got these counts:
{'auth_group': 1, 'auth_permission': 2, 'django_admin_log': 1}
Captured queries were:
1. SELECT "auth_permission"."id",...
```

Add copy&paste test in AssertQueries().assert_table_counts()

---

bx_django_utils/translation.py
bx_django_utils_tests/tests/test_admin.py
pyproject.toml

All ModelAdmin class field names attributes are tuples. Because tuples are immutable. It's a bad idea change these attributes to a mutable list. This may cause side effects.
e.g.: If a `get_readonly_fields()` manipulate the attributes for different user/permission. This changes should never mutate the base attribute!
Change `TranslationFieldAdmin` to patch the tuples also to tuples.

Generate only tuples in TranslationFieldAdmin

---

README.md
bx_django_utils/user_timezone/middleware.py
bx_django_utils_tests/tests/test_user_timezone/test_admin.py
pyproject.toml

We can't trust value of `request.COOKIES['UserTimeZone']` :)
The ZoneInfo will also check this, but pass them just to `os.path` functions. Before this we can check some basics, that this is in normal length range and has no ugly characters. Better save than sorry ;)

Validate UserTimeZone cookie value before pass it to ZoneInfo

---

bx_django_utils/test_utils/assert_queries.py
bx_django_utils_tests/tests/test_assert_queries.py

Modern Django emits unquoted table names for some complicated queries. There is no reason why we shouldn't be able to handle that.
Simplify the quote, `findall` was not necessary since we only take the first match anyways.

assert_queries: Handle unquoted table names

---

README.md
bx_django_utils/feature_flags/data_classes.py
bx_django_utils/feature_flags/exceptions.py
bx_django_utils/feature_flags/templates/admin_extra_views/manage_feature_flags.html
bx_django_utils/feature_flags/tests/test_feature_flags.py
bx_django_utils/feature_flags/utils.py
bx_django_utils_tests/tests/test_feature_flag_integration.py
bx_django_utils_tests/tests/test_feature_flag_integration_basic_1.snapshot.html
bx_django_utils_tests/tests/test_feature_flag_integration_basic_django42_1.snapshot.html
bx_django_utils_tests/tests/test_feature_flag_integration_basic_django50_1.snapshot.html
pyproject.toml

improve feature flags with some quality of life improvements
- complement `FeatureFlag.is_enabled` with the new `FeatureFlag.is_disabled`
- make the state of feature flags pythonically evaluable by implementing `FeatureFlag.__bool__`
- in the administration page, create an anchor for every flag and provide a paragraph for copying a deep link
- provide the new `@if_feature` decorator to conditionally run decorated functions (saves boilerplate evaluation code)

improve feature flags with some quality of life improvements

---

bx_django_utils/test_utils/fixtures.py

- Use `all_fixtures` (filtered) rather than `fixtures_registry` (unfiltered)
- If only one option filtered do that without asking for user input.

Fix filtering in renew_fixtures command

---

README.md
bx_django_utils/test_utils/users.py
bx_django_utils_tests/tests/__init__.py
bx_django_utils_tests/tests/test_project_setup.py
pyproject.toml

This does:
* Activate typeguard
* Expand unittest assert context length
* Deny any requests in tests

Configure unittests via "load_tests Protocol"

---

README.md
bx_django_utils/feature_flags/data_classes.py
bx_django_utils/feature_flags/tests/test_feature_flags.py

Add a reset method that will remove the current state of the feature flag completely, e.g. to get a clean development environment.

Feature Flag: add reset()

---

README.md
bx_django_utils/feature_flags/data_classes.py
bx_django_utils/feature_flags/tests/test_feature_flags.py

Store the additional name. In retrospect, it was a bad idea to name the `__init__` kwarg `cache_key`, when that has another meaning.

FeatureFlag: Add __str__ and __repr__

---

bx_django_utils_tests/tests/test_translation.py

the old one was deprecated in DJango 4.2 and removed in 5.1

use different assertion method in test

---

README.md
bx_django_utils/feature_flags/README.md
bx_django_utils/feature_flags/admin_views.py
bx_django_utils/feature_flags/data_classes.py
bx_django_utils/feature_flags/tests/test_feature_flags.py

By default, each time the flags state is evaluated (e.g. when calling `foo_feature_flag.is_enabled()`), the flag state is fetched from the underlying storage. This may cause poor performance in hot code paths.
Add optional, in-process caching capabilities to FeatureFlag by limiting evaluation of its state to once every n seconds.

Allow FeatureFlags to be more resource-efficient

---

.github/workflows/pythonapp.yml
README.md
bx_django_utils/admin_extra_views/datatypes.py
bx_django_utils/admin_extra_views/registry.py
bx_django_utils/admin_extra_views/utils.py
bx_django_utils/admin_utils/admin_urls.py
bx_django_utils/dbperf/query_recorder.py
bx_django_utils/feature_flags/data_classes.py
bx_django_utils/json_utils.py
bx_django_utils/models/manipulate.py
bx_django_utils/models/queryset_utils.py
bx_django_utils/test_utils/assert_queries.py
bx_django_utils/version.py
bx_django_utils_tests/test_app/tests/test_fixtures_helper.py
bx_django_utils_tests/test_project/settings.py
bx_django_utils_tests/tests/admin_utils/test_filters.py
bx_django_utils_tests/tests/test_admin_extra_views_index_page_django51_1.snapshot.html
bx_django_utils_tests/tests/test_feature_flag_integration_basic_django51_1.snapshot.html
bx_django_utils_tests/tests/test_html_assertion_assert_html_response_snapshot_django51_1.snapshot.html
pyproject.toml

Also run `pyupgrade --py310-plus` and `django-upgrade --target-version 4.2` against the codebase as those are our minimum supported version.
Add the `requires-python` directive to `pyproject.toml` to properly reflect our minimum Python version.

Compatibility with Django 5.1 and Python 3.13

---

Makefile
bx_django_utils_tests/test_project/publish.py
pyproject.toml
uv.lock

* Replace setuptools with the more modern hatchling.
* fix "make publish"
* call pip-audit after "make update-requirements"
* make pip-audit call faster
* create coverage report after nox call (this also cleanup coverage data files)
* Bugfix "make publish" by remove pipenv call

fix packaging

---

README.md
bx_django_utils/feature_flags/data_classes.py
bx_django_utils_tests/tests/test_feature_flag_integration.py

When the body of a context manager defined with `@contextmanager` and the iterator protocol (`yield`) raises an exception, the `yield` will raise!
Make sure we restore the flag to the previous value if that happens.

Fix temp_* functions in feature flags

---

Makefile
bx_django_utils_tests/test_app/management/commands/update_readme.py
bx_django_utils_tests/tests/test_readme.py

Normally not needed, because the README will be updated while test run. But it's helpfull to debug failing tests because of this: https://github.com/boxine/bx_django_utils/actions/runs/17424284206

Add "make update-readme"
